---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-load-balancer-tls
  namespace: kube-system
  labels:
    helm.sh/chart: aws-load-balancer-controller-1.1.4
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: legendlegendclusterchartawsloadbalancere71f3739
    app.kubernetes.io/version: "v2.1.2"
    app.kubernetes.io/managed-by: Helm
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUxQUGZJZDdXOVUyMG9VRjYzSkV2eDR3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpNVEF5TVRNeE9USXpNRGxhRncwek1UQXlNVEV4T1RJek1EbGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURzZGtvTDBBeU1qalRUMmtUci9iWEZxUWc4RzhpRW52UXZPRURtSGhqZUdZN0pna1pwRnY1UApYMjFad3Y0M1FWckFoY0VZOWl4ei9lOXBnRW5XNGMveXJVSXRRcEF5Mnd4UG9WZzdybGd1QS9xRmdFa1VPTS83CnJJcDVyc1kzMkp0M3FXc0pEZVFmTDFoQUdUNXJCM2Q2WmRSdHZFNzc4MmFGM25neGNOVGh4SkhJc1p5cTRiSU4KRjlSWnZoWG1GQnRCVWNwUlhucnVzaERSOS80ZFFMWlRRS3ZQOGE5OTI2Y29TcCtSMHJ2S3REMThOMFVPblhndgpHcDlSTE9sR1Z3bFMvR254MzREeHphcEZpeGN2Sy8xcVRXTDFGcUlFOGJaalU4YTVZU20vemppclFDZE90TTh5Ck9LTWJZS3doR3VwUHFIQWRFMHZjVUlseXEweWRyUXZyQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVaW01c1hveVZRTzg5M3NCc1hHRXpPaThOUk9Vd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBRmk3ZE14eVNMeFVKMU9tdTVUVlJ4a1h6OXh3RUJGQzVXc0JuVVl1OE9BYlpqOWg4Q0FiTVp3YTltbGEKalhIMy9Xc3VxanhQTWNLNEg1QTBscktGTmlFVjQzSTQ1SFdjNW5ELzlQS2QxQ3V4Z0s4Lys0M0R3ZUo2dDZPMQpEZUdYVDBMRVRxY0pzNlFFSzBxYWNjNTVYL1A0a1A2VFFBN0xUb2U5VmlOMGMzalg4Q1ZzZitldjZ0dStJNDBVCjczREhXaEVNanNrSlNUSHpSZEZVZkU1c01CUElIaE9JakNlOFNRWTdEdExUQ2ZneDE4aW5yK0hBRGpBRWxSQTQKMStsVlFwbDFrcVR1M0swT2xkUThHakp3d3NnQmVybW5TZFFEZWQrNGM0ekJURVI1V0xOYjErRzdqVnVRZ1FkawpRTVV4bE13RkNPazJ6anZxanpXbERGbVM1SkE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR6akNDQXJhZ0F3SUJBZ0lSQUt0dytFWUtpeFErZHF1cGk4enpGdjR3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpNVEF5TVRNeE9USXpNRGxhRncwek1UQXlNVEV4T1RJek1EbGFNRW94U0RCR0JnTlZCQU1UUDJ4bFoyVnVaR3hsCloyVnVaR05zZFhOMFpYSmphR0Z5ZEdGM2MyeHZZV1JpWVd4aGJtTmxjbVUzTVdZek56TTVMV0YzY3kxc2IyRmsKTFdKaGJHRnVZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOVE94SW1JMkZMQwpJUW5xQnNJaU5nZU5OaVRXc3M1MjNMSW5wSU1kbzBwcTYyb0dIRGZWb2lrTzQvckVxNk95Z2FKR3JZQmdPS25rCjY3SWc1NUZNWEk1bUlnNloyUHhwUHh1TElqOXJ5ZlhsNWVEblo0bkgxODJpMGNLMWx0dTBsVVhyaWRIcE5VQysKNFpaUnpnSXZKRUVZRTQ1eVRTeFBSMEJ4SVQvV2o4VXltTG5BNEY3NWhpYUdxdjcvaDFRT3hvSUtPcmttWCtndQpjVFR2T0ROVzRiWnhjV3F4TVdhbWhtWFRmaXhvVTVrZkZEdG9mUFUxbllZVjFPYXBJTW1PK2ZILy9LdVpLNmV2CnlKdStCcHc2TVRMMTBQckxQSEJLamVGckxiQ2szbHp2TEppeXFCZVJsMTJXcHAwcmxvMml5YnRsRHF0WDlGdVcKeGduODYzSk5oMmNDQXdFQUFhT0J6akNCeXpBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSQpLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVpbTVzClhveVZRTzg5M3NCc1hHRXpPaThOUk9Vd2F3WURWUjBSQkdRd1lvSXRZWGR6TFd4dllXUXRZbUZzWVc1alpYSXQKZDJWaWFHOXZheTF6WlhKMmFXTmxMbXQxWW1VdGMzbHpkR1Z0Z2pGaGQzTXRiRzloWkMxaVlXeGhibU5sY2kxMwpaV0pvYjI5ckxYTmxjblpwWTJVdWEzVmlaUzF6ZVhOMFpXMHVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCCkFRQVR5KzJxQXFCK21NNGRPRzJwbllxRjE5Y3FIRUtUaGdmTXhkS2UvN1MwV1NhZHNWN3RzQkZoSGJZdXFnNEsKUXZSSFBrY2dPSnJhdnd4enpyeUp6cVgxZ0RZdWQrdms2Mkxub0VIOXpRdDhHWXd0akM2VENmbmxvWlNldUp2cwpiQjJkQloyYng2SHpQSVdFOUJzR28vWGpCWTRRZndSaGtLT0kyNVl5U29wL2p1SHgrL3Bxak83TmlCV1B0UmluCmZNS0l6OFk2eDhKTG5GVytvdnNoNDlNTnlyZmxMZ2dRQlpTTHJDZElIWmtwdHZWMTBjQmozR0tDaC9YWXB0NDUKdmE2T01UVGxXa0wxQUZ0b0NVa29YL1dma0FKL1hnNXNpeDNabWRZZFhYL0ZhSXBiUmRZMzJwR1ZoWmwvUEJZUApkSFh3UUVKNS9pd2QxVFdmWVlaM1MwdXoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBMU03RWlZallVc0loQ2VvR3dpSTJCNDAySk5heXpuYmNzaWVrZ3gyalNtcnJhZ1ljCk45V2lLUTdqK3NTcm83S0Jva2F0Z0dBNHFlVHJzaURua1V4Y2ptWWlEcG5ZL0drL0c0c2lQMnZKOWVYbDRPZG4KaWNmWHphTFJ3cldXMjdTVlJldUowZWsxUUw3aGxsSE9BaThrUVJnVGpuSk5MRTlIUUhFaFA5YVB4VEtZdWNEZwpYdm1HSm9hcS92K0hWQTdHZ2dvNnVTWmY2QzV4Tk84NE0xYmh0bkZ4YXJFeFpxYUdaZE4rTEdoVG1SOFVPMmg4CjlUV2RoaFhVNXFrZ3lZNzU4Zi84cTVrcnA2L0ltNzRHbkRveE12WFErc3M4Y0VxTjRXc3RzS1RlWE84c21MS28KRjVHWFhaYW1uU3VXamFMSnUyVU9xMWYwVzViR0NmenJjazJIWndJREFRQUJBb0lCQVFDeFpjd2dlcHNhSWdvNApvWVlRdjBRYTkzUnpNU2JOUmZpajZyZ1JOTnV5Wlg3cFd6NmFyTlFKTmdpR092eDU4WXh2SWt2d0FFWThHa0VBCnRMMVZPanJOMmdYNTlmWVVOQWdQaGVSK3lmUUpzQ1A1WCszSHhYZjRUQXBnTGRBY1JtVkpiQmZ2akdDQUlKOGQKR0FTTGZaRFRVcWE2MEQzVStpR0Ric3N3MUVQMU5ibnl0S1FKblFiNGZUU0tVM1IzZlhRZFpQKyt4V01yQld5awpwN0t4enAvSjVmT0JVc25jRnNjc2gzUUpibHE1TlJGNU1BRE92YzZ5MDAxUjIraXFvbU9WTDJya2o4UEZObnVPCjNINkVYbDlLVDIxd042enQ3WVJSWUFjUVk1WER4Um9iVXp1Mzh3NWNRVDNOMmVtdUtYR084V1lZQnQyamREUWoKTnZiQ2kxWEJBb0dCQVAxNm04dXY4VUpRTG9rWDJscngwQXZTeDB2TmxWRXdGcWpuWEI1WnFzV0dxMmNoWkM4MQpHWlJPWjZTUlE5WWVVYlRRUWxwZ3B3R2dJY1VQY29iaWZuaXlVK25ZMnNxWXJRSy9RdURRUmtSU2tYNjdHZ2daCkh1N0ppNDh6WXNIZWF0L040ME04ZG9RN3VXeUptVE1scCtkZHFKQUNDbEJucndUV085RTA2UmxOQW9HQkFOYnMKbXN2a1MrMDNUZFplVVNiSXpRMGJDQ3F4ei9Pd1hpVy9zK2ZDcGlSazFCd3J6bS9aVFlDRy9WWE1BNzZQTzlXOApmVDcyeDYwdFNEaE5lc2RPY0pmSHo4TE9rZlNNSWV2UGpEZHkrUXM4NnBCbmVzbFRhUVBUbHNlSktyRENVVlBNCjRtZUtRR3QrS05Rd3hwS2FLU1VOMWxaYkhvZXRNaUdWbm1ybnVXbURBb0dBUmJCSjJRdzhSa0VKS2tQV2twNWMKMW9OU3E3S1AxTXhsem5ZZFMzTFhrb3JkNFBLN09vZGN5dnRyWDBGWTV5dGF4MTFpZ0xxRjc5cDRybGI2NDc2dAppcjFzZUtSWU1zOGE4ZUJub0t0aVJqSjFNZVI2MmJNZVlBUWxURytTUFQ3TEgxRFpwSWloQk9YdXFycUIxaUFLCk0zLzZjZTA5ckxGMDJ0MlRnSWNOZHhrQ2dZRUFpU3BqK0xCeERLbjVFVkVNZGJZOXQ1bUM4c3ljclNmb1RpczAKeERya0VlSVB4UkxvSTFZS01uYjBnNmM2MUlsUlpLMXhPWmdDQTdJY24ySkRjNlBLRS9RLzBsSkhzRTBtOFBwNgp3SUN1Rk5BQjI3dFBEK0lkNllWR2UzNDlNcVl4aFV3RFNwVmZXN3NlajUyNWZhTEprNDVyTnAzY3REYURBaEFkCkZKbGpLY1VDZ1lFQTZqeSs5VXdZejhpWi8zcWtkemNEQkJRUHZ0R21SVnp3Q3d4ZU1kRWtPdzVON3VJNmpCV0cKeVhEZ1k5UXdFeGxjV1djd0t5amxjOTZjSmttdXZCUlNCZEZzL2lrMVBrQ1FoRkRYcUdvOUNtMmtLUTFBVXhRcgp1OE9DRWNrbEVacXRzL3lHanB3RjNFV1hoWnB2d282WkdMWmhoekxhVVJYbUVwaTRveXhzQlZnPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
# Source: aws-load-balancer-controller/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: legendlegendclusterchartawsloadbalancere71f3739-aws-load-balanc-role
  labels:
    helm.sh/chart: aws-load-balancer-controller-1.1.4
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: legendlegendclusterchartawsloadbalancere71f3739
    app.kubernetes.io/version: "v2.1.2"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: ["elbv2.k8s.aws"]
  resources: [targetgroupbindings]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]
- apiGroups: [""]
  resources: [pods]
  verbs: [get, list, watch]
- apiGroups: ["networking.k8s.io"]
  resources: [ingressclasses]
  verbs: [get, list, watch]
- apiGroups: ["", "extensions", "networking.k8s.io"]
  resources: [services, ingresses]
  verbs: [get, list, patch, update, watch]
- apiGroups: [""]
  resources: [nodes, secrets, namespaces, endpoints]
  verbs: [get, list, watch]
- apiGroups: ["elbv2.k8s.aws", "", "extensions", "networking.k8s.io"]
  resources: [targetgroupbindings/status, pods/status, services/status, ingresses/status]
  verbs: [update, patch]
---
# Source: aws-load-balancer-controller/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: legendlegendclusterchartawsloadbalancere71f3739-aws-load-balanc-rolebinding
  labels:
    helm.sh/chart: aws-load-balancer-controller-1.1.4
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: legendlegendclusterchartawsloadbalancere71f3739
    app.kubernetes.io/version: "v2.1.2"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: legendlegendclusterchartawsloadbalancere71f3739-aws-load-balanc-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
---
# Source: aws-load-balancer-controller/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: legendlegendclusterchartawsloadbalancere71f3739-aws-load-balanc-leader-election-role
  namespace: kube-system
  labels:
    helm.sh/chart: aws-load-balancer-controller-1.1.4
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: legendlegendclusterchartawsloadbalancere71f3739
    app.kubernetes.io/version: "v2.1.2"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: [""]
  resources: [configmaps]
  verbs: [create]
- apiGroups: [""]
  resources: [configmaps]
  resourceNames: [aws-load-balancer-controller-leader]
  verbs: [get, patch, update]
---
# Source: aws-load-balancer-controller/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: legendlegendclusterchartawsloadbalancere71f3739-aws-load-balanc-leader-election-rolebinding
  namespace: kube-system
  labels:
    helm.sh/chart: aws-load-balancer-controller-1.1.4
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: legendlegendclusterchartawsloadbalancere71f3739
    app.kubernetes.io/version: "v2.1.2"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: legendlegendclusterchartawsloadbalancere71f3739-aws-load-balanc-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
---
# Source: aws-load-balancer-controller/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aws-load-balancer-webhook-service
  namespace: kube-system
  labels:
    helm.sh/chart: aws-load-balancer-controller-1.1.4
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: legendlegendclusterchartawsloadbalancere71f3739
    app.kubernetes.io/version: "v2.1.2"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: legendlegendclusterchartawsloadbalancere71f3739
---
# Source: aws-load-balancer-controller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legendlegendclusterchartawsloadbalancere71f3739-aws-load-balanc
  namespace: kube-system
  labels:
    helm.sh/chart: aws-load-balancer-controller-1.1.4
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: legendlegendclusterchartawsloadbalancere71f3739
    app.kubernetes.io/version: "v2.1.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-load-balancer-controller
      app.kubernetes.io/instance: legendlegendclusterchartawsloadbalancere71f3739
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-load-balancer-controller
        app.kubernetes.io/instance: legendlegendclusterchartawsloadbalancere71f3739
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: default
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: aws-load-balancer-tls
      securityContext:
        fsGroup: 65534
      containers:
      - name: aws-load-balancer-controller
        args:
        - --cluster-name=LegendClusterA6751FE1-16d135652b774b20b84a8c8ba807e8a
        - --ingress-class=alb
        command:
        - /controller
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        image: "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.2"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        ports:
        - name: webhook-server
          containerPort: 9443
          protocol: TCP
        - name: metrics-server
          containerPort: 8080
          protocol: TCP
        resources:
          {}
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: 61779
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 10
      terminationGracePeriodSeconds: 10
---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    helm.sh/chart: aws-load-balancer-controller-1.1.4
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: legendlegendclusterchartawsloadbalancere71f3739
    app.kubernetes.io/version: "v2.1.2"
    app.kubernetes.io/managed-by: Helm
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUxQUGZJZDdXOVUyMG9VRjYzSkV2eDR3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpNVEF5TVRNeE9USXpNRGxhRncwek1UQXlNVEV4T1RJek1EbGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURzZGtvTDBBeU1qalRUMmtUci9iWEZxUWc4RzhpRW52UXZPRURtSGhqZUdZN0pna1pwRnY1UApYMjFad3Y0M1FWckFoY0VZOWl4ei9lOXBnRW5XNGMveXJVSXRRcEF5Mnd4UG9WZzdybGd1QS9xRmdFa1VPTS83CnJJcDVyc1kzMkp0M3FXc0pEZVFmTDFoQUdUNXJCM2Q2WmRSdHZFNzc4MmFGM25neGNOVGh4SkhJc1p5cTRiSU4KRjlSWnZoWG1GQnRCVWNwUlhucnVzaERSOS80ZFFMWlRRS3ZQOGE5OTI2Y29TcCtSMHJ2S3REMThOMFVPblhndgpHcDlSTE9sR1Z3bFMvR254MzREeHphcEZpeGN2Sy8xcVRXTDFGcUlFOGJaalU4YTVZU20vemppclFDZE90TTh5Ck9LTWJZS3doR3VwUHFIQWRFMHZjVUlseXEweWRyUXZyQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVaW01c1hveVZRTzg5M3NCc1hHRXpPaThOUk9Vd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBRmk3ZE14eVNMeFVKMU9tdTVUVlJ4a1h6OXh3RUJGQzVXc0JuVVl1OE9BYlpqOWg4Q0FiTVp3YTltbGEKalhIMy9Xc3VxanhQTWNLNEg1QTBscktGTmlFVjQzSTQ1SFdjNW5ELzlQS2QxQ3V4Z0s4Lys0M0R3ZUo2dDZPMQpEZUdYVDBMRVRxY0pzNlFFSzBxYWNjNTVYL1A0a1A2VFFBN0xUb2U5VmlOMGMzalg4Q1ZzZitldjZ0dStJNDBVCjczREhXaEVNanNrSlNUSHpSZEZVZkU1c01CUElIaE9JakNlOFNRWTdEdExUQ2ZneDE4aW5yK0hBRGpBRWxSQTQKMStsVlFwbDFrcVR1M0swT2xkUThHakp3d3NnQmVybW5TZFFEZWQrNGM0ekJURVI1V0xOYjErRzdqVnVRZ1FkawpRTVV4bE13RkNPazJ6anZxanpXbERGbVM1SkE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-v1-pod
  failurePolicy: Fail
  name: mpod.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  namespaceSelector:
    matchExpressions:
    - key: elbv2.k8s.aws/pod-readiness-gate-inject
      operator: In
      values:
      - enabled
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUxQUGZJZDdXOVUyMG9VRjYzSkV2eDR3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpNVEF5TVRNeE9USXpNRGxhRncwek1UQXlNVEV4T1RJek1EbGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURzZGtvTDBBeU1qalRUMmtUci9iWEZxUWc4RzhpRW52UXZPRURtSGhqZUdZN0pna1pwRnY1UApYMjFad3Y0M1FWckFoY0VZOWl4ei9lOXBnRW5XNGMveXJVSXRRcEF5Mnd4UG9WZzdybGd1QS9xRmdFa1VPTS83CnJJcDVyc1kzMkp0M3FXc0pEZVFmTDFoQUdUNXJCM2Q2WmRSdHZFNzc4MmFGM25neGNOVGh4SkhJc1p5cTRiSU4KRjlSWnZoWG1GQnRCVWNwUlhucnVzaERSOS80ZFFMWlRRS3ZQOGE5OTI2Y29TcCtSMHJ2S3REMThOMFVPblhndgpHcDlSTE9sR1Z3bFMvR254MzREeHphcEZpeGN2Sy8xcVRXTDFGcUlFOGJaalU4YTVZU20vemppclFDZE90TTh5Ck9LTWJZS3doR3VwUHFIQWRFMHZjVUlseXEweWRyUXZyQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVaW01c1hveVZRTzg5M3NCc1hHRXpPaThOUk9Vd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBRmk3ZE14eVNMeFVKMU9tdTVUVlJ4a1h6OXh3RUJGQzVXc0JuVVl1OE9BYlpqOWg4Q0FiTVp3YTltbGEKalhIMy9Xc3VxanhQTWNLNEg1QTBscktGTmlFVjQzSTQ1SFdjNW5ELzlQS2QxQ3V4Z0s4Lys0M0R3ZUo2dDZPMQpEZUdYVDBMRVRxY0pzNlFFSzBxYWNjNTVYL1A0a1A2VFFBN0xUb2U5VmlOMGMzalg4Q1ZzZitldjZ0dStJNDBVCjczREhXaEVNanNrSlNUSHpSZEZVZkU1c01CUElIaE9JakNlOFNRWTdEdExUQ2ZneDE4aW5yK0hBRGpBRWxSQTQKMStsVlFwbDFrcVR1M0swT2xkUThHakp3d3NnQmVybW5TZFFEZWQrNGM0ekJURVI1V0xOYjErRzdqVnVRZ1FkawpRTVV4bE13RkNPazJ6anZxanpXbERGbVM1SkE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
  failurePolicy: Fail
  name: mtargetgroupbinding.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - targetgroupbindings
  sideEffects: None
---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    helm.sh/chart: aws-load-balancer-controller-1.1.4
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: legendlegendclusterchartawsloadbalancere71f3739
    app.kubernetes.io/version: "v2.1.2"
    app.kubernetes.io/managed-by: Helm
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUxQUGZJZDdXOVUyMG9VRjYzSkV2eDR3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpNVEF5TVRNeE9USXpNRGxhRncwek1UQXlNVEV4T1RJek1EbGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURzZGtvTDBBeU1qalRUMmtUci9iWEZxUWc4RzhpRW52UXZPRURtSGhqZUdZN0pna1pwRnY1UApYMjFad3Y0M1FWckFoY0VZOWl4ei9lOXBnRW5XNGMveXJVSXRRcEF5Mnd4UG9WZzdybGd1QS9xRmdFa1VPTS83CnJJcDVyc1kzMkp0M3FXc0pEZVFmTDFoQUdUNXJCM2Q2WmRSdHZFNzc4MmFGM25neGNOVGh4SkhJc1p5cTRiSU4KRjlSWnZoWG1GQnRCVWNwUlhucnVzaERSOS80ZFFMWlRRS3ZQOGE5OTI2Y29TcCtSMHJ2S3REMThOMFVPblhndgpHcDlSTE9sR1Z3bFMvR254MzREeHphcEZpeGN2Sy8xcVRXTDFGcUlFOGJaalU4YTVZU20vemppclFDZE90TTh5Ck9LTWJZS3doR3VwUHFIQWRFMHZjVUlseXEweWRyUXZyQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVaW01c1hveVZRTzg5M3NCc1hHRXpPaThOUk9Vd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBRmk3ZE14eVNMeFVKMU9tdTVUVlJ4a1h6OXh3RUJGQzVXc0JuVVl1OE9BYlpqOWg4Q0FiTVp3YTltbGEKalhIMy9Xc3VxanhQTWNLNEg1QTBscktGTmlFVjQzSTQ1SFdjNW5ELzlQS2QxQ3V4Z0s4Lys0M0R3ZUo2dDZPMQpEZUdYVDBMRVRxY0pzNlFFSzBxYWNjNTVYL1A0a1A2VFFBN0xUb2U5VmlOMGMzalg4Q1ZzZitldjZ0dStJNDBVCjczREhXaEVNanNrSlNUSHpSZEZVZkU1c01CUElIaE9JakNlOFNRWTdEdExUQ2ZneDE4aW5yK0hBRGpBRWxSQTQKMStsVlFwbDFrcVR1M0swT2xkUThHakp3d3NnQmVybW5TZFFEZWQrNGM0ekJURVI1V0xOYjErRzdqVnVRZ1FkawpRTVV4bE13RkNPazJ6anZxanpXbERGbVM1SkE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-elbv2-k8s-aws-v1beta1-targetgroupbinding
  failurePolicy: Fail
  name: vtargetgroupbinding.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - targetgroupbindings
  sideEffects: None
